### ISSUE TITLE
fix: arbitrum Cruve Tricrypto address on vaults overview

### ISSUE THREAD

**Issue by FoxTheSin** [yearn/yearn-meta#171]
The arbitrum vault TriCrypto, on it's vault overview page, is only pointing to curve.fi instead of https://arbitrum.curve.fi/tricrypto

**Comment by karelianpie** [comment]
@FoxTheSin just a tip that if you add certain words before the issue in the PR and it gets merged, it will close the issue automagically. See here https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

For example, in the PR https://github.com/yearn/yearn-meta/pull/172 if you had written in the description the following text it would have closed this issue:

Closes https://github.com/yearn/yearn-meta/issues/171

**Comment by FoxTheSin** [comment]
> @FoxTheSin just a tip that if you add certain words before the issue in the PR and it gets merged, it will close the issue automagically. See here https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 
> For example, in the PR #172 if you had written in the description the following text it would have closed this issue:
> 
> Closes #171

<3 Thank you Karelian.
